[project]
name = "codr"
version = "0.0.1"
description = "Codr is an ai tool for faster coding."
authors = [
    { name = "Shroominic", email = "contact@shroominic.com" }
]
dependencies = [
    "funcchain>=0.1",
    "python-dotenv",
    "typer>=0.9",
    "tiktoken>=0.4",
    "pyyaml>=6",
    "aiofiles>=23",
    "pydantic-settings>=2",
    "emoji>=2",
    "rich>=13.5",
]
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
codr = 'codr.__main__:app'

[tool.rye]
managed = true
dev-dependencies = [
    "pre-commit>=3.3",
    "ruff>=0.1.5",
    "mypy>=0.991",
    "pytest>=7.2"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = "tests/codebases/*"
